### ISSUE TITLE
Thanks, 

### ISSUE THREAD

**Issue by theely** [jessfraz/dockerfiles#131]
Hi Jessie,
inspired by your blog post and the Docker file you are sharing here I wrote this blog post:
https://medium.com/@EliaPalme/scalable-ajax-crawling-on-docker-with-chrome-and-no-display-4560af08dff5#.6tmy1atk0

Maybe this Dockerfile - Gits could be of interest to you:
https://gist.github.com/theely/7ab9eb5a7e4b17c20a170d353324d849

**Comment by rain1024** [comment]
Hi theely,

Your docker file looks interesting

I'm building a crawler based on chrome. I really want to run it into docker.

I build image from dockerfile successfully. But when I run it, I get an error

```
docker run --privileged newsriver.io/dyn-crawler-test https://www.redbulletin.com/us/us/lifestyle/experience-air-to-air-combat-like-a-fighter-pilot
Starting ChromeDriver (v2.9.248304) on port 15694
[0.173][WARNING]: PAC support disabled because there is no system implementation
Exception in thread "main" org.openqa.selenium.WebDriverException: chrome not reachable
  (Driver info: chromedriver=2.9.248304,platform=Linux 3.10.0-327.18.2.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.24 seconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 16:57:40'
System info: host: '553f98a70322', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-327.18.2.el7.x86_64', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.chrome.ChromeDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:170)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:159)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:116)
	at DynamicCrawler.main(DynamicCrawler.java:6)
```

Can you explain that?

PS: I run docker 1.11 in CentOS with root user.

**Comment by jfrazelle** [comment]
For debugging dockerfiles maybe see #docker on IRC, it's very hard for me to find a fix based off this without knowing the context of what the dockerfile actually looks like, I'm good but I'm not that good ;)

**Comment by theely** [comment]
Hi @rain1024 ,
looks like the current stable version of Chrome is not so stable after all, unfortunately I don't recall the exact version number i was running when I wrote the article. I would suggest you to replace "google-chrome-stable" in the Docker file with an exact version of Chrome (e.g. "google-chrome-stable-44.0.2403.155-1.x86_64") and test it. A good approach would be to start with the last version and decrement the version number till you find a stable one that works well with selenium. If you find any could you please send me add a comment to: https://gist.github.com/theely/7ab9eb5a7e4b17c20a170d353324d849 I will than correct the Docker file.

p.s. @jfrazelle the Docker file is locate here: https://gist.github.com/theely/7ab9eb5a7e4b17c20a170d353324d849

**Comment by rain1024** [comment]
hi @theely 

Today, I'm very happy when I run image [jess/chrome](https://hub.docker.com/r/jess/chrome/) in Ubuntu (still don't work with CentOS 7. I don't know what happend with centos).

Our crawler base on chrome extension instead of selenium. Have you tried inject chrome extension in chrome image?

**Comment by theely** [comment]
@rain1024 nope, could you provide me with more informations? Do you have some examples to share?
